src/controllers/user/user.controller.ts, src/middleware/user/index.ts, src/middleware/user/updateDateOfUser.middleware.ts, src/routes/user/user.router.ts, src/validators/user/adminPatchUserValidator.ts
=> Admin can edit any user profile

.eslintrc.js, src/controllers/course/course.controller.ts, src/controllers/group/group.controller.ts, src/controllers/module/module.controller.ts, src/controllers/user/user.controller.ts, src/database/models/course.schema.ts, src/database/models/group.model.ts, src/database/models/user.schema.ts, src/interfaces/course.model.ts, src/interfaces/group.model.ts, src/middleware/group/isGroupPresent.middleware.ts, src/middleware/user/updateDateOfUser.middleware.ts, src/routes/course/course.router.ts, src/routes/user/user.router.ts, src/services/course/course.service.ts, src/services/group/group.service.ts, src/services/module/module.service.ts, src/services/user/user.service.ts, src/validators/course/index.ts, src/validators/course/modulesListValidator.ts, src/validators/group/groupFilterValidator.ts, src/validators/group/groupUpdateValidator.ts, src/validators/group/groupValidator.ts, src/validators/module/moduleValidator.ts, src/validators/user/adminPatchUserValidator.ts, src/validators/user/userFiterValidator.ts, tsconfig.json
+create Courses
+edit Courses
+delete Courses
+add/delete modules to course
=> admin can:

src/database/models/user.schema.ts
Create additional field in User schema
=> [BE][ADMIN] LMS-78

package-lock.json, package.json, src/controllers/module/module.controller.ts, src/routes/module/module.router.ts, src/services/module/module.service.ts
=> [BE][ADMIN] LMS-181

src/database/models/user.schema.ts, src/interfaces/user.model.ts, src/validators/user/adminPatchUserValidator.ts, src/validators/user/registerDataValidator.ts, src/validators/user/updateDataValidator.ts, src/validators/user/userFiterValidator.ts
Add functional for user with city
=> [BE][ADMIN] LMS-184

src/controllers/group/group.controller.ts, src/database/models/group.model.ts, src/interfaces/group.model.ts, src/middleware/group/index.ts, src/middleware/group/isGroupAttendanceValid.middleware.ts, src/routes/group/group.router.ts, src/services/group/group.service.ts, src/validators/group/groupAttendanceValidator.ts, src/validators/group/index.ts
Create basic layout for visit log
=> [BE][ADMIN] LMS-150

src/controllers/group/group.controller.ts, src/helpers/group/check-deleted-users.helper.ts, src/helpers/group/index.ts, src/helpers/index.ts, src/services/user/user.service.ts
Fix bug with add group in user
=> [BE][ADMIN] LMS-188

src/controllers/city/city.controller.ts, src/database/models/user.schema.ts, src/interfaces/user.model.ts, src/services/city/city.service.ts, src/validators/user/adminPatchUserValidator.ts, src/validators/user/registerDataValidator.ts, src/validators/user/updateDataValidator.ts, src/validators/user/userFiterValidator.ts
=> [BE][ADMIN] LMS-186

src/controllers/course/course.controller.ts, src/database/models/module.schema.ts, src/helpers/index.ts, src/helpers/module/check-deleted-modules.helper.ts, src/helpers/module/index.ts, src/services/course/course.service.ts, src/services/module/module.service.ts
=> [BE][ADMIN] LMS-193

package-lock.json, src/controllers/course/course.controller.ts, src/controllers/group/group.controller.ts, src/controllers/lesson/lesson.controller.ts, src/helpers/check-deleted-objects.helper.ts, src/helpers/group/check-deleted-users.helper.ts, src/helpers/group/index.ts, src/helpers/index.ts, src/helpers/module/check-deleted-modules.helper.ts, src/helpers/module/index.ts, src/interfaces/question.model.ts, src/services/question/question.service.ts, src/validators/lesson/addQuestionToLessonValidator.ts
Add lesson_id in question functional
=> [BE][ADMIN] LMS-200

src/services/course/course.service.ts, src/services/group/group.service.ts, src/services/lesson/lesson.service.ts, src/services/module/module.service.ts, src/services/question/question.service.ts, src/services/user/user.service.ts
=> [BE][ADMIN] LMS-195

src/controllers/lesson/lesson.controller.ts, src/controllers/module/module.controller.ts, src/interfaces/module.model.ts, src/middleware/module/index.ts, src/middleware/module/isLessonListValid.middleware.ts, src/middleware/module/isModulePresent.middleware.ts, src/routes/lesson/lesson.router.ts, src/routes/module/module.router.ts, src/services/lesson/lesson.service.ts, src/services/module/module.service.ts, src/validators/module/index.ts, src/validators/module/lessonListValidator.ts
Add functional for delete and add lesson of module
=> [BE][ADMIN] LMS-196

src/validators/module/moduleValidator.ts
=> [BE][ADMIN] LMS-203

src/controllers/module/module.controller.ts, src/services/module/module.service.ts
Add functional for edit module
=> [BE][ADMIN] LMS-202

package-lock.json, package.json, src/controllers/module/module.controller.ts, src/middleware/auth/checkEmailPresent.ts, src/services/question/question.service.ts, src/validators/user/registerDataValidator.ts
=> [BE][ADMIN] LMS-204

src/services/lesson/lesson.service.ts
=> [BE][ADMIN] LMS-207

src/controllers/module/module.controller.ts, src/controllers/user/user.controller.ts, src/database/models/user.schema.ts, src/routes/lesson/lesson.router.ts, src/services/lesson/lesson.service.ts, src/services/user/user.service.ts
Create passed test schema and add functional for her
=> [BE][ADMIN] LMS-206

src/controllers/module/module.controller.ts, src/services/lesson/lesson.service.ts, src/validators/course/courseValidator.ts, src/validators/module/moduleValidator.ts
=> [BE][ADMIN] LMS-210

src/constants/enums/dataBaseTable.enum.ts, src/controllers/lesson/lesson.controller.ts, src/database/models/comment.schema.ts, src/database/models/index.ts, src/errors/errors.ts, src/interfaces/comment.model.ts, src/interfaces/index.ts, src/middleware/lesson/index.ts, src/middleware/lesson/isCommentPresent.middleware.ts, src/middleware/lesson/isLessonCommentariesDataValid.middleware.ts, src/routes/lesson/lesson.router.ts, src/services/comment/comment.service.ts, src/services/comment/index.ts, src/services/index.ts, src/validators/lesson/index.ts, src/validators/lesson/lessonCommentariesDataValidator.ts
Create functional for commentaries
=> [BE][ADMIN] LMS-212

src/constants/enums/dataBaseTable.enum.ts, src/controllers/question/question.controller.ts, src/database/models/index.ts, src/database/models/lesson.schema.ts, src/database/models/passed_lesson.schema.ts, src/database/models/passed_question.schema.ts, src/database/models/user.schema.ts, src/interfaces/index.ts, src/interfaces/lesson.model.ts, src/interfaces/passed_lesson.model.ts, src/interfaces/passed_question.model.ts, src/interfaces/request-extended.model.ts, src/interfaces/test_result.model.ts, src/interfaces/user.model.ts, src/services/lesson/lesson.service.ts, src/services/question/question.service.ts
=> [BE][ADMIN] LMS-213

src/controllers/group/group.controller.ts, src/controllers/user/user.controller.ts, src/database/models/user.schema.ts, src/errors/errors.ts, src/helpers/group/editVisitLog.helper.ts, src/helpers/group/index.ts, src/helpers/index.ts, src/interfaces/group.model.ts, src/interfaces/passed_lesson.model.ts, src/interfaces/test_result.model.ts, src/interfaces/user.model.ts, src/middleware/group/index.ts, src/middleware/group/isVisitLogPresent.middleware.ts, src/routes/group/group.router.ts, src/routes/user/user.router.ts, src/services/group/group.service.ts, src/services/user/user.service.ts
Student passed tests activity and change - delete attendances
=> [BE][ADMIN] LMS-214

.gitignore, package-lock.json, package.json, src/app.ts, src/constants/enums/google_config.enum.ts, src/constants/enums/index.ts, src/controllers/lesson/lesson.controller.ts, src/helpers/google-deleter.helper.ts, src/helpers/google-uploader.helper.ts, src/helpers/index.ts, src/middleware/lesson/index.ts, src/middleware/lesson/isLessonValid.middleware.ts, src/routes/lesson/lesson.router.ts, src/services/lesson/lesson.service.ts
=> [BE][ADMIN] LMS-215

package-lock.json, src/database/models/user.schema.ts, src/interfaces/user.model.ts
Confirm email for registration and reset password
=> [BE][ADMIN] LMS-217

src/database/models/user.schema.ts, src/interfaces/user.model.ts
Change user password functional
=> [BE][ADMIN] LMS-218

src/controllers/lesson/lesson.controller.ts, src/validators/lesson/lessonValidator.ts
=> [BE][ADMIN] LMS-219
